### ISSUE TITLE
Establish Anki connection

### ISSUE THREAD

**Issue by StephanAkkerman** [StephanAkkerman/FluentAI#1]
See [FluentForeverVocabBuilder](https://github.com/cofinley/FluentForeverVocabBuilder) on how to do this

- [AnkiConnect add-on](https://foosoft.net/projects/anki-connect/) (code 2055492159)
- Currenlty only supports adding image cards to 2. Picture Words model deck

**Comment by StephanAkkerman** [comment]
Maybe consider change deck template to add more information: IPA string, other wikitionary info, etc.

**Comment by WinstonLam** [comment]
Anki connection is succesfull see backend-anki-api branch for the anki.py script and execution of main
