### ISSUE TITLE
Try out sana model

### ISSUE THREAD

**Issue by StephanAkkerman** [StephanAkkerman/FluentAI#107]
https://github.com/NVlabs/Sana

**Comment by StephanAkkerman** [comment]
Wait for the diffusers implementation before working on it: https://github.com/huggingface/diffusers/pull/9982

**Comment by StephanAkkerman** [comment]
We could also test the branch before it being merged for now

**Comment by StephanAkkerman** [comment]
We will probably use: https://huggingface.co/Efficient-Large-Model/Sana_600M_512px_diffusers

**Comment by TimKoornstra** [comment]
Diffusers 0.32.0 just released; it should feature [SanaPipeline](https://huggingface.co/docs/diffusers/v0.32.0/en/api/pipelines/sana#sanapipeline)
