### ISSUE TITLE
Check if models are downloaded upon API start

### ISSUE THREAD

**Issue by TimKoornstra** [StephanAkkerman/FluentAI#108]
1. Description:

   - Problem:
     I finally have everything set up, then I make the call to the `create_card` and BOOM I now 30 mins later loading models! I could download when I'm trying to fix frontend next time!

   - Solution:
     Download and load model on startup.

   - Prerequisites:
     Programming skills

2. Tasks:
   - Move loading
   - Test
   - ???
   - Success

3. Additional context
N/A

**Comment by StephanAkkerman** [comment]
There must be a method to use the huggingface lirbaries to check if the models and datsets have been downloaded and if not start the download (but not yet use them)

**Comment by TimKoornstra** [comment]
https://huggingface.co/docs/huggingface_hub/v0.26.3/en/package_reference/file_download#huggingface_hub.hf_hub_download

Might help

**Comment by StephanAkkerman** [comment]
@TimKoornstra https://huggingface.co/docs/huggingface_hub/main/en/package_reference/file_download#huggingface_hub.snapshot_download is what we need, because hf_hub_download restricts us to a single file

**Comment by StephanAkkerman** [comment]
It might be better to just load the models and delete it as snapshot_download will also download files that we do not need and take longer (especially for the LLM and image gen models)

**Comment by StephanAkkerman** [comment]
Check if the models already exist by checking if there is a directory in /models
The model folder should be named like `models--<author>`--<model name>`
