### ISSUE TITLE
Sync languages list front-end and back-end instead hardcoded json

### ISSUE THREAD

**Issue by WinstonLam** [StephanAkkerman/FluentAI#112]
1. Description:

   - Problem:
     [Briefly describe the issue or gap that needs to be addressed.]
     Right now the languages support on front-end and back-end are based on hardcoded json files

   - Solution:
     [Outline the proposed action or changes to resolve the problem. If none yet, leave blank]
    provide one languages file that the front-end and back-end both will use

   - Prerequisites:
     [List any requirements or dependencies needed before starting.]

2. Tasks:
   - Task 1
   - Task 2
   - Task 3
   - etc.

3. Additional context

**Comment by TimKoornstra** [comment]
Or should the frontend make a call to the backend to load the available languages? This makes just one service responsible for the json, and no problems with syncing between services will arise

**Comment by StephanAkkerman** [comment]
We currently have the list saved in cosntants/languages.py this should be changed into a json for all the constants the front-end uses

**Comment by StephanAkkerman** [comment]
@TimKoornstra I have added the language to data/languages.json so it's in sync with the back-end. Is it possible to let CardGenerator.tsx also use this data?

**Comment by TimKoornstra** [comment]
Finished IMO
