### ISSUE TITLE
Try disk offloading for models

### ISSUE THREAD

**Issue by StephanAkkerman** [StephanAkkerman/FluentAI#163]
1. Description:

   - Problem:
     The current implementation deletes all the variables 

   - Solution:
    Try offloading the model to disk: https://huggingface.co/docs/accelerate/en/package_reference/big_modeling#accelerate.disk_offload

   - Prerequisites:
     [List any requirements or dependencies needed before starting.]

2. Tasks:
   - Task 1
   - Task 2
   - Task 3
   - etc.

3. Additional context

**Comment by TimKoornstra** [comment]
Alternatively, we could try using `.to('cpu')`to offload to RAM. This might require a lot of RAM, however

**Comment by StephanAkkerman** [comment]
@TimKoornstra Still need to use torch.cuda.empty_cache() but definitely has better performance than the current implementation.
```python
self.model.to("cuda")
        output = self.pipe(self.messages + [final_message], **self.generation_args)
        response = output[0]["generated_text"]
        logger.debug(f"Generated cue: {response}")
        self.model.to("cpu")
        # Clear vram
        torch.cuda.empty_cache()
        import time

        time.sleep(5)
        return response
```
![image](https://github.com/user-attachments/assets/e96cf7ab-5f1a-40bf-a52c-cc10cc1a6e97)

**Comment by StephanAkkerman** [comment]
Because this increases RAM we should keep the current implementation for deletion (and make it part of the class) and also add the new implementation as config option
