### ISSUE TITLE
Create GUI

### ISSUE THREAD

**Issue by StephanAkkerman** [StephanAkkerman/FluentAI#5]
Maybe use the same implementation as [vocab builder repo](https://github.com/cofinley/FluentForeverVocabBuilder), using flask.

It should cover:
- Initial setup process where the models & datasets are downloaded (user should be able to track this progress)
  - Maybe we should then already test if the user's PC meets all the requirements
  - Here the user also needs to specify the foreign language it wants to learn for #8 
- The creation of new vocab cards
  - Fill in: English word
  - Find nearest word in preferred foreign language (selection of top x)
  - Generate mnemonic sentence (ability to regenerate / adjust manually)
  - Generate mnemomic image (ability to regenerate / adjust parameters)
  - Combine them into Anki flash card and save it to deck
- Creation of grammar cards
- More?

**Comment by StephanAkkerman** [comment]
@WinstonLam deze kan worden aangepast of verwijderd worden in de plaats van de ts front-end

**Comment by WinstonLam** [comment]
Decided to opt for React frontend in TS for better UI capabilities in Future

**Comment by WinstonLam** [comment]
migrated to #64
