### ISSUE TITLE
Basic Front-end for user input 

### ISSUE THREAD

**Issue by WinstonLam** [StephanAkkerman/FluentAI#64]
1. Description:

   - Problem:
    Initial setup for the front-end for user interaction with the services. 

   - Solution:
     the front-end initially will consist of:
     - homepage
     - cardgeneration page
     - card library

   - Prerequisites:
     Currently built using node might switch to deno in future

2. Tasks (components for the front-end):
- [x] StephanAkkerman/FluentAI#66
- [x] StephanAkkerman/FluentAI#67
- [x] StephanAkkerman/FluentAI#68
- [x] StephanAkkerman/FluentAI#70
- [x] StephanAkkerman/FluentAI#69

3. Additional context
In future iterations we focus on:

Initial setup process where the models & datasets are downloaded (user should be able to track this progress)
Maybe we should then already test if the user's PC meets all the requirements
Here the user also needs to specify the foreign language it wants to learn for https://github.com/StephanAkkerman/FluentAI-pro/issues/10
The creation of new vocab cards
Fill in: English word
Find nearest word in preferred foreign language (selection of top x)
Generate mnemonic sentence (ability to regenerate / adjust manually)
Generate mnemomic image (ability to regenerate / adjust parameters)
Combine them into Anki flash card and save it to deck
Creation of grammar cards
More?

**Comment by StephanAkkerman** [comment]
The process for creating the grammar cards is linked to #7 but not yet detailed

**Comment by StephanAkkerman** [comment]
#8 is for the languages the user wants to learn IN, for now only English is supported until #8 is done. The supported languages to learn are described in: https://github.com/StephanAkkerman/FluentAI/blob/main/supported-languages.md
