### ISSUE TITLE
Create Seperate folder explaining pyenv for virtual python env

### ISSUE THREAD

**Issue by WinstonLam** [StephanAkkerman/FluentAI#97]
1. Description:

   - Problem:
     Currently the project doesn't offer clear support for python venv
   - Solution:
     Created a dedicated folder with a ReadME on how users can achieve this
   - Prerequisites:
     installation of pyenv

2. Tasks:
   - Add folder
   - Add ReadME
   - - install pyenv
   - - eval "$(pyenv init --path)" (might be needed if homebrew installation of pyenv)
   - - pyenv install pythonversion (install your needed python version)
   - - pyenv local pythonversion (set the local python version for your project)
   - - run python -m venv yourenvname.env
   - - source yourevnname.env/bin/activate (to activate the python venv)

**Comment by StephanAkkerman** [comment]
Is dit niet voor elke python project hetzelfde? Of moeten users echt wat anders doen voor dit tov een ander python project?

**Comment by WinstonLam** [comment]
No longer needed as focus will be shifted to containerization
